### ISSUE TITLE
BSWH -  Internal Testing Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1023]
Placeholder. DevOps will be providing the internal testing checklist for Operations review.

**Comment by Gbarra9** [comment]
PWA Internal Test Checklist from Box(https://nih.app.box.com/file/1530633892003): 

- [ ] BSWH as a healthcare site option on sign up

- [ ] IHCS confirmation pop up says BSWH

- [ ] Consent screens - same

- [ ] BSWH HTML consent form V0.02 (2/13/2024)

- [ ] BSWH HTML HIPAA form V0.01 (01/24/2024) 

- [ ] BSWH unsigned consent PDF V0.02 (2/13/2024) - on every page

- [ ] BSWH unsigned consent PDF download document name

- [ ] BSWH unsigned HIPAA PDF V0.01 (01/24/2024)

- [ ] BSWH unsigned HIPAA download document name

- [ ] BSWH signed consent PDF (page after consent) (Before UP) V0.02 (2/13/2024)

- [ ] BSWH signed consent PDF (page after consent) (Before UP) signature coordinates

- [ ] BSWH signed HIPAA PDF (page after consent) (before UP) V0.01 (01/24/2024)

- [ ] BSWH signed HIPAA PDF (page after consent) (before UP) signature coordinates 

- [ ] User profile - should look the same 

- [ ] Pre-verification message (should look the same)

- [ ] BSWH MySamples page - pre-verification

- [ ] BSWH MySamples page - post-verification

- [ ] Dashboard with questionnaires - (should look the same)

- [ ] BSWH signed consent PDF from "Forms" tab V0.02 (2/13/2024)

- [ ] BSWH signed consent PDF from "Forms" tab signature coordinates

- [ ] BSWH signed HIPAA form from "Forms" tab V0.01 (01/24/2024) 

- [ ] BSWH signed HIPAA form from "Forms" tab- signature coordinates

**Comment by robertsamm** [comment]
@Gbarra9 I edited the SMDB testing checklist to add the last two scenarios to test as well. These testing checklists look good. Thanks for creating!

**Comment by Gbarra9** [comment]
> @Gbarra9 I edited the SMDB testing checklist to add the last two scenarios to test as well. These testing checklists look good. Thanks for creating!

@robertsamm  Thanks for adding the additional two. The checklist items are copied from box.
