### ISSUE TITLE
Data destruction notification bug testing - Testing Checklist

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1045]
Hello Everyone, Please see the below checklist for data destruction notification bug testing. Testing checklist is linked to Issue #1034, no new variables will need to be retained in stub variables.

We ask that you review the list and check off the item with your initial and date of completion.

- [x] @mnataraj92 to schedule and facilitate a walk through of the data destruction testing plan in her absence (6/27)
- [x] @jhflorey to alert the team when fix is in Dev 7/2 JF
- [ ] @KELSEYDOWLING7  and @rebexxxxxx to work on Jing's code and confirm when code is ready
- [x] @cunnaneaq to create test participants in Dev - Done 6/26
- [x] Data destruction was not tested during Madhuri's absence so @mnataraj92 to lead data destruction dev testing 7/16
- [ ] For stage testing, @HanaShiho / @cunnaneaq to reach out to site to create participants for stage testing (same test scenarios as in dev)
- [ ] @HanaShiho / @cunnaneaq to reach out to the site for the biospecimen collections for stage (same test scenarios as in dev)
- [ ] @mnataraj92 to send invite to the team for stage testing
- [ ] @robertsamm or @kmazzilli to request data destruction for appropriate scenarios and sign data destruction form for appropriate scenario in dev and stage during testing
- [x] @KELSEYDOWLING7 / @rebexxxxxx / @rohanjay10 to check the data to make sure correct data is destroyed properly in dev and stage - (7/30 RJ)
- [ ] @HanaShiho to modify notification cadence to daily for dev and stage testing to ensure notifications are going out as expected for the appropriate scenarios where data destruction has been requested and to ensure that not all notifications are going out at once. Scenarios where notifications are not expected should not have notifications sent out. 
- [ ] @HanaShiho to check SMDB and notifications during dev and stage testing
- [ ] @KELSEYDOWLING7 / @rebexxxxxx to confirm that notification table data in BQ is deleted for appropriate scenarios and retained for appropriate scenarios during dev and stage testing
- [ ] @wyattks  / @erincschwartz to check Biospecimen DB during dev and stage testing
- [ ] @jhflorey will run the data destruction program in dev and stage during testing
- [x] @jacobmpeters to sync Big Query with Firestore in dev and stage during testing **[JP 7/16]**

**Comment by rebexxxxxx** [comment]
I have completed the 2 data destruction requests included in the DD SOP for DEV data (tables 1+2: https://nih.app.box.com/file/1540404957592). You can find the results of these queries here: https://app.box.com/s/z8tybqtgoskwfqwwawxlruncw58p1ith.  The first two sheets correspond to the Table 1 query. Connect_ids were isolated by their affirmative response for data destruction. The sheet "query1_table1_counts" contains the number of null and non null values for the variables listed in table 1, by connect_ID. Sheet 2, "query1_other_variables" contains the number of null and non null values of the remaining variables in the participants table, by connect_ID. 

The third sheet in the spreadsheet, "query2_all_table_counts", corresponds to the 2nd table in the DD SOP. This request asked for a confirmation that all data listed in table 2 is either destroyed or preserved. A frequency table was created to count the number of null and non null variable values by connect_id by table. If a connect_id and table were not listed in this sheet, then no data for any connect_ids were found.

**Comment by brotzmanmj** [comment]
Hi @rebexxxxxx Thanks for this summary. For this 'by their affirmative response for data destruction' can you confirm you're using the variable that indicate they are eligible for data destruction (not the one that indicates they have requested data destruction)?

And then who is assigned to check this next?

**Comment by KELSEYDOWLING7** [comment]
Hi @brotzmanmj  we had thought because this was specifically for data destruction backend testing, this would only apply to those who have had their data destroyed (HdWd_DataHasBnDestroyed_v1r0=yes). Once the testing starts we'd use to check that all stub variables are saved, and to check if each the tables from the SOP are saved/deleted

**Comment by rohanjay10** [comment]
Hi @KELSEYDOWLING7 when checking the backend data we would be accounting for the below 3 factors (and their conditions) to help determine DD eligibility. The 3rd point indicates if a participant is eligible for DD(which I believe is what @brotzmanmj is referring to).
I believe these factors would be worked into the testing plan as well. 
1. Check for participants who didn't request data destruction
2. Check for participants who requested data destruction but are not qualified to have their data destroyed.
3. Check for participants who have requested data and are qualified to have their data destroyed.

**With variable names and conditions**
1. Check for participants who didn't request data destruction.
-DD Requested(HdWd_Destroydata_v1r0 = no)

2. Check for participants who requested data destruction but are not qualified to have their data destroyed.
-DD Requested(HdWd_Destroydata_v1r0 = yes)
AND
DD form not signed(HdWd_Datadestroysign_v1r0=no)
AND
It has been less than 60 days since
Date of DD request (HdRef_DateDatadestroy_v1r0) 

3. Check for participants who have requested data and are qualified to have their data destroyed.
 -DD Requested(HdWd_Destroydata_v1r0 = yes)
AND
DD form signed
(HdWd_Datadestroysign_v1r0=yes) 
OR
DD Requested(HdWd_Destroydata_v1r0 = yes)
AND
DD form has not been signed(HdWd_Datadestroysign_v1r0=no)
AND
It has been 60 days or greater since 
Date of DD request(HdRef_DateDatadestroy_v1r0)

@brotzmanmj Let me know if the above conditions have to be changed.

Regarding testing, I am not sure how different it will be from last time. But for previous dev and stage DD testing, Jing would make a 'before' and 'after' column for each test participant to check values before and after DD was run. As you mentioned, we would then do checks to make sure all the stub vars are retained and have expected values, the other variables are deleted, and the other tables from the SOP are saved or deleted.

**Comment by KELSEYDOWLING7** [comment]
@rohanjay10  Thanks for clarifying, we may or may not need to change the code then. 

@rebexxxxxx 
I'm thinking your current code should work just about as is, we'd just have to run them before data destruction is tested and save those counts and compare to after the data destruction is completed.  We'd also have to update the current conditionality (HdWd_DataHasBnDestroyed_v1r0=yes) to the conditionality listed above for each scenario. It might be easiest to just repeat the code three times with the three different conditionality scenarios. Let me know if that makes sense, we can also meet again on Monday.

**Comment by KELSEYDOWLING7** [comment]
Apologizes, we didn't realize we'd have to have code for all three of these scenarios. We'll need more time to work on the code and Rebecca is out on Monday

**Comment by brotzmanmj** [comment]
That's fine, thanks

**Comment by rebexxxxxx** [comment]
hi @brotzmanmj @robertsamm @rohanjay10, the code for data destruction testing is ready to go! @KELSEYDOWLING7 and I are available for testing on Thursday.

**Comment by robertsamm** [comment]
Hi @rebexxxxxx and @KELSEYDOWLING7 great news about the code! Since Madhuri will be back on Friday, Michelle suggested we wait until she is back to lead the testing.
