### ISSUE TITLE
PROMIS Backlog Survey Trigger Testing Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1099]
- [x] @HanaShiho / @rohanjay10 / @mnataraj92 to create test scenarios - 8/13
- [x] @cunnaneaq to create test participants in dev - 8/14
- [x] @Gbarra9 to verify participants according to specific verification dates outlined in the test scenarios 
- [x] @mnataraj92 to send out dev testing invite to the team, scheduled August 19th - 8/14
- [x] @cunnaneaq to create test participants/reach out to the site to create test participants for stage testing 
- [x] @mnataraj92 to send out invite for stage testing- set for 8/26
- [x] @jhflorey to add stage pts to code for 8/26 testing
- [x] @jhflorey to be on standby during the testing to troubleshoot

**Comment by sonyekere** [comment]
https://nih.app.box.com/file/1616227727906
