### ISSUE TITLE
NORC Phone Prompting Testing Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1100]
- [x] @mnataraj92 to create test scenarios - 8/14
- [x] @jacobmpeters and @rohanjay10 to review test scenarios based on requirements - 8/14
- [x] @cunnaneaq to create test participants in Dev - 8/15 
- [x] @Gbarra9 to verify participants according to the scenarios, this will be done Tuesday, August 20th AM 
- [x] @cunnaneaq to fill out surveys according to scenarios, this will be done Tuesday, August 20th AM 
- [x] @jacobmpeters to run his report on Tuesday, August 20th PM 
- [x] @mnataraj92 and @rohanjay10 to review Jake's report and verify that report looks as expected and all variables are included 
- [x] @cunnaneaq to create stage participants/ ask the site to create test participants in stage 
- [x] @jacobmpeters to run his report in stage 
- [x] @mnataraj92 and @rohanjay10 to review Jake's report in stage 
- [x] @jacobmpeters send NORC a test file by August 26th

**Comment by sonyekere** [comment]
https://nih.app.box.com/file/1621640899021
