### ISSUE TITLE
Connect Experience Survey Testing Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1115]
Link to testing plan: 

Hello Everyone, Please see the below checklist for testing. We ask that you review the list and check off the item with your initial and date of completion.

- [ ] @mnataraj92  and @HanaShiho  to create test scenarios - done and sent to Michelle for review 
- [ ] @cunnaneaq  to create test participants in dev and @Gbarra9  to verify participants - done 
- [ ] @mnataraj92  to send out testing invitations for the week of 9/23 for dev testing (likely Tuesday, 9/24 in case code is not ready yet to be tested) 
- [ ] @HanaShiho  to modify notification cadence for testing 
- [ ] @cunnaneaq  to trigger survey in PWA during dev testing, @HanaShiho  to check notifications, @kmazzilli  to check SMDB 
- [ ] @cunnaneaq  to reach out to site to create stage participants 
- [ ] @mnataraj92  to send out invitation for stage testing 
- [ ] @cunnaneaq  to trigger survey in PWA during stage testing, @HanaShiho  to check notifications, @kmazzilli  to check SMDB 
- [ ] @bransteitterbr or (@Gbarra9 as backfill if needed) to check firestore during dev and stage testing

**Comment by jacobmpeters** [comment]
@sonyekere When there is a collection added to Firestore for a new survey, it typically needs to be configured to be transferred to BigQuery. Once it is backed up to the `Connect` dataset in BigQuery, I can flatten it for the Analytics team.

Can your team confirm whether experience survey collection will be included in the transfer to BQ? We'll need this to be done for backend checks after testing.. 

I think @we-ai is most familiar with the backup process.

**Comment by sonyekere** [comment]
Thanks @jacobmpeters for the alert and context. Davin agrees that Warren would be best positioned to take this on. Also from talking to Madhuri it doesn't seem like this would impact testing currently, but I would like your feedback here. Is this something we can prioritize in the October release or is this a request that should be addressed now?

**Comment by jacobmpeters** [comment]
@sonyekere Ok. I think you are right that it won't affect the current testing seems to just involve flags in the participant table, but IMS has been asking about when the tables will be available in BigQuery and whether we will need them to check the data on their end. That is want prompted me to ask about whether the new collection is configured to be included in the BQ transfer once the survey has been tested. I'll share the IMS correspondence for context.

**Comment by we-ai** [comment]
The "experience2024" collection in Firestore should also be synced to BQ for stage and prod tiers, right?

**Comment by jacobmpeters** [comment]
@we-ai Yes, I believe so.

**Comment by we-ai** [comment]
Data sync works as expected in dev tier. @jacobmpeters Let me know if you find anything wrong.
If no additional change is needed, the updated code for "experience 2024" data sync will be pushed to stage and prod.
