### ISSUE TITLE
Testing Checklist - Data Destruction request  'any refusal/withdrawal' & participation status variables'

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1139]
Please see below the testing checkin list for issue #1117 
- [x] @mnataraj92  creates test plan & Michelle reviews (10/14 )
- [x] @cunnaneaq  creates dev test pts ( 10/15)
- [x] @cunnaneaq  pushes refusals/withdrawals according to scenario 
- [x] @jhflorey  checks 'any refusal/withdrawal' and 'participation status' variables in firestore, @KELSEYDOWLING7  checks those vars in BQ (they can check that today or tmrw i guess)
- [x] @mnataraj92  & @rohanjay10  confirm that back end matches the responses for those variables that we expect to see
- [x] @mnataraj92 , @cunnaneaq , @rohanjay10 , @jhflorey , @KELSEYDOWLING7 Repeat in stage once code is pushed to stage on October 28th
