### ISSUE TITLE
Testing Checklist - NORC and DevOps Release Items (API data exchange, Birthday card return, Survey reset & Incentive eligible tool)

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1140]
Please see the below testing checklist.

**Birthday card return data** #888 
- [x] NORC to create test scenarios and send us bday card data via API (this will be during the week of dev testing provided NORC is ready to send us data)
- [ ] @KELSEYDOWLING7  and @JoeArmani to check BQ and firestore to make sure that the data NORC sends us is in the correct structure/format. 
- [ ] Birthday card data table to be configured so it can be added and flattened to BQ
- [ ] This will be done in dev and stage 

**For the API streamlined for data exchange** #1126
- [ ] NORC should generate lists for the phone prompting participants and the birthday card recipients via API. 
- [ ] @jacobmpeters  will run those same lists and upload to box
- [ ]  Analytics team (@jacobmpeters / @KELSEYDOWLING7  / Leila) will generate code to do a comparison of the reports that NORC generates via API and the reports that Jake generates on our end to make sure they're the same. 
- [ ] This will be done in dev and stage 

**NORC survey reset tool** #1130 - Moved to November Release
- [x] Tony/Gene/dev ops to confirm that deleting the variables won't impact anything downstream that it shouldn't. (Deleting variables may cause problems downstream. It was discussed on 10/16 that completely wiping survey data may not be optimal. The tool could reset surveys that have been started but not yet submitted, If survey data will need to be deleted, then this might be done manually. The tool will first be used on the SSN survey) 
- [ ] @cunnaneaq  to create test participants that have the surveys filled out, and NORC to use tool to reset the surveys. 
- [ ] @KELSEYDOWLING7 / @Gbarra9/ @JoeArmani   to confirm on back end that data has been deleted/reset as expected. 
- [ ] This will be done in dev and stage.

**Incentive eligible tool** #1131 - Moved to November Release
- [ ]  Aileen will create test pt that is not yet incentive eligible (ex: completed all baseline modules but was unable to complete blood draw or something)
- [ ] NORC to use tool to make pt incentive eligible. 
- [ ] @KELSEYDOWLING7 / @Gbarra9 / @JoeArmani  to check BQ and firestore. 
- [ ] This will be done in dev and stage.
