### ISSUE TITLE
Cancer Screening Survey Test Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1158]
Link to testing plan: https://nih.app.box.com/file/1696442979647

Hello Everyone, Please see the below checklist for testing. We ask that you review the list and check off the item with your initial and date of completion.

- [ ] @mnataraj92 to create test scenarios - DONE 11/13
- [ ] Michelle to review test plan 
- [ ] @cunnaneaq to create test participants in Dev (DONE 11/13)  and Stage (PENDING) 
- [ ] @mnataraj92 to send out Dev and Stage invite 
- [ ] @lorszag to check numbers before testing for how many are eligible vs non eligible for the survey 
- [ ] @HanaShiho to test email notifications during testing in Dev/ Stage and to modify notification cadence as required 
- [ ] @depietrodeanna to develop content for the notification reminder emails in Dev and Stage 
- [ ] @HanaShiho If Deanna is unable to complete the above (develop content email reminders), please set up place holder content to go out for the emails in Dev and Stage 
- [ ] If Deanna is unable to develop content for the email notifications by the time dev testing begins, @HanaShiho and @depietrodeanna to test offline to ensure that the email content looks as expected( test having 1st/2nd/3rd etc reminders go out w/finalized content w/test pts eligible for the survey)
- [ ] @kmazzilli / @HanaShiho /  @depietrodeanna / @cunnaneaq to check PWA and SMDB as needed during Dev and Stage testing
- [ ] @we-ai to check back end in firestore during testing in Dev and Stage 
- [ ] @KELSEYDOWLING7 / @lorszag to check BigQuery in Dev and Stage  
- [ ] @HanaShiho to monitor stop dates

**Comment by lorszag** [comment]
As of 11/14/24:

In dev, n(eligible) = 31
In stage, n (eligible) = 554

``` sql
SELECT Connect_ID
FROM `nih-nci-dceg-connect-stg-5519.FlatConnect.participants_JP`
WHERE Connect_ID is not null
  AND d_821247024 = "197316935"                             -- RcrtV_Verification_v1r0 = 1
  AND DATE_DIFF(CURRENT_DATE(), CAST(LEFT(d_914594314, 10) AS DATE), DAY) >= 270   -- Today - RcrtV_VerificationTm_V1R0 >= 270
  AND d_747006172 = "104430631"                             -- HdWd_WdConsent_v1r0 = 0```
