### ISSUE TITLE
NORC Incentive Eligibility and Survey Reset Tool Test Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1159]
Link to testing plan: https://nih.app.box.com/file/1692224312451

Hello Everyone, Please see the below checklist for testing. We ask that you review the list and check off the item with your initial and date of completion.

- [ ] @mnataraj92 to create test scenarios, @rohanjay10 / Sandra to review requirements and UI with @Gbarra9 (RJ 11/15)
- [ ] Michelle to review the test plan 
- [ ] @cunnaneaq to create test ppts in Dev and Stage 
- [ ] @mnataraj92 / Sandra to send a test invite in Dev and Stage 
- [ ] NORC to demo the tools live during testing 
- [ ] @Gbarra9 to check the back end to make sure that data is updating in firestore based on the actions that NORC enables using the tool 
- [ ] @mnataraj92 /Sandra to reach out to the site to make sure that the tool is not visible on their end
