### ISSUE TITLE
User Profile Enhancements Testing Checklist 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1160]
Link to testing plan:

Hello Everyone, Please see the below checklist for testing. We ask that you review the list and check off the item with your initial and date of completion.

- [ ] @mnataraj92 and @robertsamm to create test scenarios in Dev and Stage 
- [ ] Michelle to review test plan 
- [ ] @cunnaneaq to create ppts in Dev and Stage 
- [ ] Sandra to follow up on the  F&R request by tomorrow (11/15),  for (2) sites to volunteer to help test in Dev
- [ ] Sites will not need to join the call, they will push data offline 
- [ ] @kmazzilli  / @depietrodeanna / @cunnaneaq  to check SMDB and PWA as needed during Dev and Stage testing 
- [ ] @jhflorey to check backed in firestore 
- [ ] @KELSEYDOWLING7 / @lorszag to check BigQuery
